### ISSUE TITLE
Will Damage your Computer message

### ISSUE THREAD

**Issue by ordotools** [anhmv/DeathCounter#3]
After installing Death Counter for all users on my MacBook Pro 2019 running Monterey, I get a message saying that the `.saver` file will damage my computer. This dialog box appears after I try to set the options for the screensaver using System Preferences.

**Comment by johnnygoodface** [comment]
Yeap me too. An example of the message (I know it's not "helper", but you get the idea):

<img width="787" alt="Screen Shot 2022-02-23 at 10 21 16 AM" src="https://user-images.githubusercontent.com/24813857/155349553-ce1a83df-54a9-4d25-bf02-7bd2935fbeea.png">

**Comment by mcvnh** [comment]
@corei8 @johnnygoodface Sorry guys, I didn't maintain this screensaver for a while, it's better to clone the source code and build your own, since my developer certificate was expired.
